# Generated by Django 4.0.6 on 2022-07-25 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Назва товару')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Назва товару')),
                ('SKU', models.TextField(verbose_name='SKU товару')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('descr', models.TextField(verbose_name='Опис товару')),
                ('short_descr', models.TextField(verbose_name='Короткий опис товару')),
                ('image', models.ImageField(upload_to='shop/products/image', verbose_name='Іконка товару')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
        migrations.CreateModel(
            name='CartUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Кількість')),
                ('cart_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart', verbose_name='Кошик')),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Продуки')),
            ],
            options={
                'verbose_name': 'Юніт кошику',
                'verbose_name_plural': 'Юнити кошику',
            },
        ),
    ]
