# Generated by Django 4.0.6 on 2022-07-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartunit',
            name='cart_fk',
        ),
        migrations.RemoveField(
            model_name='cartunit',
            name='product_fk',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartUnit',
        ),
    ]
